config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :groups do
        resources :tasks, :controller => 'group_tasks' do
            collection do
                post :bulk_destroy
            end
        end
        collection do
            get "overview" => "groups#overview"
            get :search
        end
    end
    root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :tasks, dependent: :destroy
    belongs_to :user
    validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :group
    belongs_to :user
    validates :text, presence: true
    validates :group_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :groups
  has_many :tasks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/group_tasks_controller.rb
class GroupTasksController < ApplicationController
    # index, show, new, edit, create, update and destroy.
    before_action :set_group, :except => :bulk_destroy
    before_action :set_task, :only => [:show, :edit, :update, :destroy]
    before_action :set_search
    before_action :authenticate_user!

    def index
        @tasks = @group.tasks
    end
    
    def show
        @group = @task.group_id
    end
    
    def new
        @task = @group.tasks.build
    end
    
    def edit
    end
    
    def create
        @task = @group.tasks.build(task_params)
        @task.user = current_user
        if @task.save
            redirect_to group_tasks_path(@group)
        else
            render :action => :new
        end
    end
    
    def update
        if @task.update(task_params)
            redirect_to :action => :index
        else
            render :action => :edit, :id => @task
        end
    end
    
    def destroy
        @task.destroy
        
        flash[:alert] = "Task was successfully deleted!"
        
        redirect_to :action => :index
    end
    
    def bulk_destroy
        ids = Array(params[:ids])
        tasks = ids.map{|id| Task.find_by_id(id)}
        tasks.each{ |t| t.destroy}
        
        redirect_to overview_groups_path
    end
    
    private
    
    def task_params
        params.require(:task).permit(:text, :group_id, :ddl, :emergency, :user_id)
    end
    
    def set_group
        @group = Group.find(params[:group_id])
        @groups = current_user.groups
        @head = @group.name
    end
    
    def set_task
        @task = @group.tasks.find(params[:id])
    end
    
    def set_search
        @q = Task.ransack(params[:q])
    end
end
    

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    # index, show, new, edit, create, update and destroy
    before_action :authenticate_user!
    before_action :set_groups
    before_action :set_group, :only => [:edit, :update, :destroy]
    before_action :set_groups_and_search

    
    def index
    end
    
    def overview
        @q = Task.ransack(params[:q])
        @tasks = current_user.tasks
    end
    
    def new
        @group = current_user.groups.build
    end
    
    def edit
    end
    
    def create
        @group = current_user.groups.build(group_params)
        @group.user = current_user
        if @group.save
            redirect_to :action => :index
        else
            render :action => :new
        end
    end
    
    def update
        if @group.update(group_params)
            redirect_to group_tasks_path(@group.id)
        else
            render :action => :edit, :id => @group
        end
    end
    
    def destroy
        if @group.id == current_user.groups.first.id
            flash[:alert] = "Group " + @group.name + " cannot be deleted."
        else
            @group.destroy
            flash[:alert] = "Group " + @group.name + " was successfully deleted!"
        end
        
        redirect_to groups_path
    end
    
    def search
        @q = params[:q] if params[:q].present?
        @search_criteria = {text_cont: @q}
        if @q.present?
            @tasks = Task.ransack(@search_criteria).result(:distinct => true)
        end
    end
    
    private
    
    def set_group
        @group = Group.find(params[:id])
    end
    
    def group_params
        params.require(:group).permit(:name, :user_id)
    end
    
    def set_groups_and_search
        @q = Task.ransack(params[:q])
    end
    
    def set_groups
        @groups = current_user.groups
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        if current_user
            @groups=current_user.groups
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <br>
    <div class="alert alert-danger"
    style="font-family: Arial, Helvetica, sans-serif; font-size: 17px;">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/group_tasks_helper.rb
module GroupTasksHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/group_tasks/_form.html.erb
<div id="form_head"><%= f.label :text, "Your task" %></div><br>
<%= f.text_area :text, class: "form-control" %><br>

<div id="form_head"><%= f.label :ddl, "Deadline" %></div><br>
<%= f.date_select :ddl, :order => [:day, :month, :year]%><br>

<div id="form_head"><%= f.label :group, "Group" %></div><br>
<%= f.collection_select(:group_id, current_user.groups, :id, :name) %><br>

<div id="form_head"><%= "Is it an urgent task?" %></div><br>
<%= f.radio_button(:emergency, "yes") %>
<%= f.label(:emergency, "Yes") %>
<%= f.radio_button(:emergency, "no") %>
<%= f.label(:emergency, "No") %>

<% if @task.errors.any? %>
	<ul class="alert alert-danger">
	<% @task.errors.full_messages.each do |msg| %>
		<li> <%= msg %> </li>
	<% end %>
	</ul>
<% end %>

app/views/group_tasks/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" style="top: 0px;">
  
  <div class="navbar-header">
    <div class="navbar-brand">
      <%= link_to "Todo-Manager", groups_path %>
    </div>
  </div>
  
  <% if current_user %>
    <div class="btn-group">
      <%= link_to'Log out', destroy_user_session_path, :method => :delete %> |
      <%= link_to'Change Password', edit_registration_path(:user) %>
    </div>
  <% else %>
    <div class="btn-group">
      <%= link_to'Register', new_registration_path(:user) %> |
      <%= link_to'Log in', new_session_path(:user) %>
    </div>
  <% end %>
  
  <% @groups.each do |g| %>
    <% if g.id %>
      <ul class="nav navbar-nav">
        <li><%= link_to g.name, group_tasks_path(g) %></li>
      </ul>
    <% end %> 
  <%end%>
  
  <div class="form-inline">
    <%= form_tag url_for(:action=>:search,:controller=>:groups), :method => :get do %>
      <%= search_field_tag :q, params[:q], placeholder: "Search tasks", class: "form-control" %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <%end%>
  </div>

</nav>

app/views/group_tasks/edit.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<%= form_for ([@group, @task]) do |f| %> 

	<%= render :partial => 'form', :locals => {:f => f} %><br>
	<br>
	<%= f.submit "Update", class: " btn btn-warning btn-block" %>

<% end %> 

<br><%= link_to 'Homepage', group_tasks_path(@group), class: " btn btn-primary btn-block" %>

app/views/group_tasks/index.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<h2 id="pageTitle"> <%= @head %></h2>

<div style="float:right">
<%= link_to 'Rename Group', edit_group_path(@group), class:"btn btn-outline-warning" %>
<%= link_to 'Delete Group', group_path(@group), :method => :delete, :data => {:confirm => "Are you sure to delete this group? 
PLEASE NOTE YOUR FIRST GROUP CANNOT BE DELETED!"}, class:"btn btn-outline-danger" %>
</div><br>

<%= form_tag bulk_destroy_group_tasks_path(:group_id => 0) do %>
	<table class = "table table-striped table-hover">
		<tr style="font-family: 'Arial Black', Gadget, sans-serif">
			<th></th>
			<th>Text</th>
			<th>Deadline</th>
			<th>Action</th>
		</tr>
		
		<% @tasks.each do |t| %>
			<% if t.emergency == 'yes' %>
				<tr style="text-align:center" class="bg-primary text-white">
					<td><%= check_box_tag "ids[]", t.id, false %></td>
					<td><%= t.text %></td>
					<td><%= t.ddl %></td>
					<td>
						<div class="btn-group">
						<%= link_to 'Show', group_task_path(@group, t), class:"btn btn-light" %>
						<%= link_to 'Edit', edit_group_task_path(@group, t), class:"btn btn-outline-light" %>
						<%= link_to 'Delete', group_task_path(@group, t), :method => :delete, :data => {:confirm => "Are you sure to delete this task?"}, class:"btn btn-light" %>
					</td>
				</tr>
			<% else %>
				<tr style="text-align:center">
					<td><%= check_box_tag "ids[]", t.id, false %></td>
					<td><%= t.text %></td>
					<td><%= t.ddl %></td>
					<td>
						<div class="btn-group">
						<%= link_to 'Show', group_task_path(@group, t), class:"btn btn-primary" %>
						<%= link_to 'Edit', edit_group_task_path(@group, t), class:"btn btn-outline-primary" %>
						<%= link_to 'Delete', group_task_path(@group, t), :method => :delete, :data => {:confirm => "Are you sure to delete this task?"}, class:"btn btn-primary" %>
					</td>
			<% end %>
		<% end %>
		
	</table>

	<br><%= link_to 'Create', new_group_task_path, class:"btn btn-success btn-block" %>
	<br><%= submit_tag 'Delete', class:"btn btn-danger btn-block", :data => {:confirm => "Are you sure to delete the selected tasks?"} %>
	<br><%= link_to 'Back', groups_path, class:"btn btn-primary btn-block" %>
<%end%>

app/views/group_tasks/new.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<%= form_for [@group, @task] do |f| %> 

	<%= render :partial => 'form', :locals => {:f => f} %><br>
	<br>
	<%= f.submit "Create", class: " btn btn-success btn-block" %>

<% end %> 

<br><%= link_to 'Homepage', groups_path, class: " btn btn-primary btn-block" %>

app/views/group_tasks/show.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<div id="details">
<strong>Text:</strong>
<%= @task.text %><br>

<strong>Deadline:</strong>
<%= @task.ddl %><br>

<strong>Group:</strong>
<%= Group.find(@task.group_id).name %><br>
</div>

<br>
<%= link_to 'Homepage', groups_path, class: "btn btn-primary btn-block" %>
 

app/views/groups/_form.html.erb
<div id="form_head"><%= f.label :name, "Your group" %></div><br>
<%= f.text_area :name, class: "form-control" %><br>

<% if @group.errors.any? %>
	<ul class="alert alert-danger">
	<% @group.errors.full_messages.each do |msg| %>
		<li> <%= msg %> </li>
	<% end %>
	</ul>
<% end %>

app/views/groups/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" style="top: 0px;">
  
  <div class="navbar-header">
    <div class="navbar-brand">
      <%= link_to "Todo-Manager", groups_path %>
    </div>
  </div>
  
  <% if current_user %>
    <div class="btn-group">
      <%= link_to'Log out', destroy_user_session_path, :method => :delete %> |
      <%= link_to'Change Password', edit_registration_path(:user) %>
    </div>
  <% else %>
    <div class="btn-group">
      <%= link_to'Register', new_registration_path(:user) %> |
      <%= link_to'Log in', new_session_path(:user) %>
    </div>
  <% end %>
  
  <% @groups.each do |g| %>
    <% if g.id %>
      <ul class="nav navbar-nav">
        <li><%= link_to g.name, group_tasks_path(g) %></li>
      </ul>
    <% end %> 
  <%end%>
  
  <div class="form-inline">
    <%= form_tag url_for(:action=>:search,:controller=>:groups), :method => :get do %>
      <%= search_field_tag :q, params[:q], placeholder: "Search tasks", class: "form-control" %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <%end%>
  </div>

</nav>

app/views/groups/edit.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<%= form_for @group do |f| %> 

	<%= render :partial => 'form', :locals => {:f => f} %><br>
	<br>
	<%= f.submit "Update", class: " btn btn-warning btn-block" %>

<% end %> 

<br><%= link_to 'Homepage', groups_path, class: " btn btn-primary btn-block" %>

app/views/groups/index.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<% if current_user.groups.first %>
	<h1 id="pageTitle">Groups</h1>

	<div style="font-family: 'Arial Black', Gadget, sans-serif">
	<% @groups.each do |group| %>
		<%= link_to group.name, group_tasks_path(group), class: "btn btn-default btn-block" %> 
		<br>
	<% end %>
	</div>

	<br><%= link_to 'Create a New Group', new_group_path, class: "btn btn-success btn-block"%>
	<br><%= link_to 'Create a New Task', new_group_task_path(current_user.groups.first), class: "btn btn-success btn-block"%>
	<br><%= link_to 'View All Tasks', overview_groups_path, class: "btn btn-primary btn-block" %>
<% else %>
	<div id="welcome">
		<br>
		<%= "Please create your first group immediately."%><br><br>
		<%= "Only then you can create your tasks."%><br><br>
		<%= link_to 'Create', new_group_path, class:"btn btn-success"  %>
	</div>
<% end %>

app/views/groups/new.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<%= form_for @group do |f| %> 

	<%= render :partial => 'form', :locals => {:f => f} %><br>
	<br>
	<%= f.submit "Create", class: " btn btn-success btn-block" %>

<% end %> 

<br><%= link_to 'Homepage', groups_path, class: " btn btn-primary btn-block" %>

app/views/groups/overview.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

	<h2 id="pageTitle"> Todo List </h2>

<%= form_tag bulk_destroy_group_tasks_path(:group_id => 0) do %>
<table class="table table-striped table-hover">
	<tr style="font-family: 'Arial Black', Gadget, sans-serif">
		<th></th>
		<th>Text</th>
		<th>Group</th>
		<th>Action</th>
	</tr>
	
	<% @tasks.each do |t|%>
		<% group=Group.find(t.group_id) %>
		<% if t.emergency == 'yes' %>
			<tr style="text-align:center" class="bg-primary text-white">
				<td><%= check_box_tag "ids[]", t.id, false %></td>
				<td><%= t.text %></td>
				<td style="font-weight:bold" ><%= group.name%></td>
				<td>
					<div class="btn-group">
						<%= link_to 'Show', group_task_path(group, t), class:"btn btn-light" %>
						<%= link_to 'Edit', edit_group_task_path(group, t), class:"btn btn-outline-light" %>
						<%= link_to 'Delete', group_task_path(group, t), :method => :delete, :data => {:confirm => "Are you sure to delete this task?"}, class:"btn btn-light" %>
					</div>
				</td>
			</tr>
		<% else %>
			<tr style="text-align:center">
				<td><%= check_box_tag "ids[]", t.id, false %></td>
				<td><%= t.text %></td>
				<td style="font-weight:bold" ><%= group.name%></td>
				<td>
					<div class="btn-group">
						<%= link_to 'Show', group_task_path(group, t), class:"btn btn-primary" %>
						<%= link_to 'Edit', edit_group_task_path(group, t), class:"btn btn-outline-primary" %>
						<%= link_to 'Delete', group_task_path(group, t), :method => :delete, :data => {:confirm => "Are you sure to delete this task?"}, class:"btn btn-primary" %>
					</div>
				</td>
			</tr>
		<% end %> 
	<% end %>
			
</table>

<br><%= link_to 'Create', new_group_task_path(Group.first), class:"btn btn-success btn-block" %>
<br><%= submit_tag 'Delete', class:"btn btn-danger btn-block", :data => {:confirm => "Are you sure to deleted the selected tasks?"} %>
<br><%= link_to 'Homepage', groups_path, class:"btn btn-primary btn-block"  %>
<%end%>

app/views/groups/search.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<% if current_user.groups.first %>
	<h1>
		<div id="pageTitle">
			<%= "Search Results For: " %>
			<%= @q %>
		</div>
	</h1>

	<% if @tasks.empty? %>
		<div style="font-family: 'Arial Black', Gadget, sans-serif;
					color: red;
					font-size: 20px;">
			<br><%= "You don't have such tasks in the list." %>
		</div>
		<div style="font-size: 20px;">
			<br><%= "Is it you forgot to add it?" %>
			<br><%= link_to 'Create Now', new_group_task_path(current_user.groups.first), class:"btn btn-success" %>
			<br><br><%= "Or just leave?" %>
			<br><%= link_to 'Homepage', groups_path, class:"btn btn-primary" %>
		</div>
	<% else %>
		<table class = "table table-striped table-hover">
			<tr style="font-family: 'Arial Black', Gadget, sans-serif">
				<th>Text</th>
				<th>Deadline</th>
			</tr>
			<% @tasks.each do |t| %>
			<tr style="text-align:center">
				<% @group = t.group.id %>
				<td><%= link_to t.text, group_task_path(@group, t) %></td>
				<td><%= t.ddl %></td>
			</tr>
			<% end %>
		</table>
		<br>
		<%= link_to 'Homepage', groups_path, class:"btn btn-primary btn-block" %>
	<%end%>
<% else %>
	<div id="welcome">
		<br>
		<%= "Please create your first group immediately."%><br><br>
		<%= "There is no point to search without creating your own task."%><br><br>
		<%= link_to 'Create', new_group_path, class:"btn btn-success"  %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @head || "Todo Manager" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      #header {
        background-color: #157efb;
        color: white;
        padding: 5px;
        line-height: 60px;
        font-size: 50px;
        font-family: 'Arial Black', Gadget, sans-serif;
        text-align: center;
        font-variant: small-caps;
        top: 0px;
      }
      #pageTitle {
        text-align: center;
        color: #157efb;
        font-family: 'Arial Black', Gadget, sans-serif;
        font-variant: small-caps;
      }
      #text {
        line-height: 60px;
      }
      #details {
        line-height: 60px;
        text-align: center;
        font-size: 30px;
      }
      #alert {
        color: red;
        text-align: center;
        font-family: 'Arial Black', Gadget, sans-serif;
      }
      #notice {
        color: green;
        text-align: center;
        font-family: 'Arial Black', Gadget, sans-serif;
      }
      #form_head {
        color: #157efb;
        line-height: 20px;
        font-size: 20px;
        position: relative;
        bottom: -20px;
        font-family: 'Arial Black', Gadget, sans-serif;
      }
      #user {
        line-height: 20px;
        top: -30px;
        background-color: #157efb;
        color: white;
      }
      #welcome {
        font-family: 'Arial Black', Gadget, sans-serif; 
        color: #157efb;
        font-size: 20px;
      }
    </style>
  </head>

  <body>
    <div id="main-container" class="container-fluid" >
      <div class="row"> 
        <div class="col-md-12" id="header"> Todo Manager </div>
      </div>
      <div class="row"> 
        <div class="col-md-12 container-fluid" id="pageTitle"">
          <%= yield :navbar %>
          <p id="notice"><%=flash[:notice]%></p>
          <p id="alert"><%=flash[:alert]%></p>
        </div>
      </div>
      <div class="row" style="text-align:center">
        <div class="col-md-3"></div>
        <div class="col-md-6">
        <%= yield %>
        </div>
        <div class="col-md-3"></div>
      </div>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %> 

	<%= render :partial => 'form', :locals => {:f => f} %>
	<%= f.submit "Update" %>

<% end %> 

<%= link_to 'Homepage', root_path %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %> 

	<%= render :partial => 'form', :locals => {:f => f} %>
	<%= f.submit "Create" %>

<% end %> 

<%= link_to 'Homepage', root_path %>

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" style="top: 0px;">
  
  <div class="navbar-header">
    <div class="navbar-brand">
      <%= link_to "Todo-Manager", groups_path %>
    </div>
  </div>
  
  <% if current_user %>
    <div class="btn-group">
      <%= link_to'Log out', destroy_user_session_path, :method => :delete %> |
      <%= link_to'Change Password', edit_registration_path(:user) %>
    </div>
    <% @groups.each do |g| %>
      <ul class="nav navbar-nav">
        <li><%= link_to g.name, group_tasks_path(g) %></li>
      </ul>
    <%end%>
  <% else %>
    <div class="btn-group">
      <%= link_to'Register', new_registration_path(:user) %> |
      <%= link_to'Log in', new_session_path(:user) %>
    </div>
  <% end %>


  
  <div class="form-inline">
    <%= form_tag url_for(:action=>:search,:controller=>:groups), :method => :get do %>
      <%= search_field_tag :q, params[:q], placeholder: "Search tasks", class: "form-control" %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <%end%>
  </div>

</nav>

app/views/welcome/index.html.erb
<% content_for :navbar do %>
	<%= render 'navbar' %>
<%end%>

<% if current_user %>
	<div id="welcome">
		<br>
		<%= "Welcome!"%>
		<br><br>
		<%= "You have signed in as " + current_user.email %>
		<br><br>
		<div class="alert alert-success">
		<%= "Please note" %>
		  <ol>
		  	<li><%= "You MUST have at least one group before creating a task." %></li>
		  	<li><%= "Your first created group CANNOT be deleted." %></li>
		  </ol>
		</div>
		<br>
		<%= "If you haven't create your first group "%><br>
		<%= link_to 'Create', new_group_path, class:"btn btn-success"  %>
		<br><br>
		<%= link_to 'View Your Task Groups', groups_path, class:"btn btn-primary"  %>

	</div>
<% else %>
	<div id="welcome">
		<br>
		<%= "Please sign in to enjoy your journey with"%>
		<br><br>
		<div style="font-size: 30px;"><%= "Todo-Mangager!" %></div>
      		<br><br>
		<%= link_to'Sign up', new_registration_path(:user), class:"btn btn-success" %>
      		<%= link_to'Log in', new_session_path(:user), class:"btn btn-primary" %>
	</div>
<% end %>